name: Daily Updates

"on":
  workflow_dispatch: ~
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          show-progress: false
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          repository: 'aclemons/slackbuilds'
          path: 'slackbuilds'
          show-progress: false
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          repository: 'aclemons/slackrepo-local-hints'
          path: 'slackrepo-local-hints'
          show-progress: false
      - run: |
          git clone --depth 1 git://git.slackbuilds.org/slackbuilds.git slackbuilds.org
      - run: |
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" SLACKBUILDS_DIR="$(pwd)/slackbuilds.org" MYSLACKBUILDS_DIR="$(pwd)/slackbuilds" HINTS_DIR="$(pwd)/slackrepo-local-hints" ./.github/workflows/bin/run-monitor
      - uses: aclemons/xmpp-notifier@bceed0f7a8fff10c5ca0fb9976adfe617b5edfdd
        with:
          jid: ${{ secrets.XMPP_JID }}
          password: ${{ secrets.XMPP_PASSWORD }}
          server_host: ${{ secrets.XMPP_HOST }}
          recipient: ${{ secrets.XMPP_ROOM }}
          message: ${{ env.UPDATES }}
          recipient_is_room: true
