name: Daily Updates

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: processone/xmpp-notifier@63f9120194390db3283f89527b8f16e8bd8a3115 # v1.0.0
        with:
          jid: ${{ secrets.XMPP_JID }}
          password: ${{ secrets.XMPP_PASSWORD }}
          server_host: ${{ secrets.XMPP_HOST }}
          recipient: ${{ secrets.XMPP_ROOM }}
          message: |
            test
          recipient_is_room: true
